// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetEmailStatusRequest struct {
	Id string `path:"id"`
}

type GetEmailStatusResponse struct {
	Id         string   `json:"id"`
	Template   string   `json:"template"`
	Recipients []string `json:"recipients"`
	Subject    string   `json:"subject"`
	Status     string   `json:"status"`
	Attempts   int      `json:"attempts"`
	Error      string   `json:"error,omitempty"`
	CreatedAt  string   `json:"created_at"`
}

type GetTemplateRequest struct {
	Slug string `path:"slug"`
}

type GetTemplateResponse struct {
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

type ListEmailsRequest struct {
	Status string `form:"status,optional"`
	Limit  int    `form:"limit,default=50"`
}

type ListEmailsResponse struct {
	Emails []GetEmailStatusResponse `json:"emails"`
	Count  int                      `json:"count"`
}

type ListTemplatesResponse struct {
	Templates []TemplateItem `json:"templates"`
	Count     int            `json:"count"`
}

type RenderTemplateRequest struct {
	Slug string `path:"slug"`
}

type RenderTemplateResponse struct {
	Html     string `json:"html"`
	Template string `json:"template"`
	Size     int    `json:"size"`
}

type SendEmailRequest struct {
	Template string            `json:"template"`
	To       []string          `json:"to"`
	Subject  string            `json:"subject"`
	Data     map[string]string `json:"data,optional"`
}

type SendEmailResponse struct {
	Id         string `json:"id"`
	Status     string `json:"status"`
	Recipients int    `json:"recipients"`
	Template   string `json:"template"`
}

type StatsResponse struct {
	Stats map[string]int `json:"stats"`
	Total int            `json:"total"`
}

type TemplateItem struct {
	Slug        string `json:"slug"`
	Description string `json:"description"`
}
