version: '3'

dotenv:
  - .env

vars:
  DATA_DIR: '{{.ROOT_DIR}}/.data'
  BIN_DIR: '{{.ROOT_DIR}}/.bin'

tasks:
  # Build
  build:
    desc: Build server binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/server ./cmd/server

  build:cli:
    desc: Build CLI binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/plat-mjml .

  # Setup
  deps:
    desc: Install dependencies and tools
    cmds:
      - go mod download
      - go install github.com/zeromicro/go-zero/tools/goctl@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - echo "For VSCode, install the goctl extension from marketplace"
      - echo "  https://marketplace.visualstudio.com/items?itemName=xiaoxin-technology.goctl"

  # CLI Commands
  run:
    desc: Run CLI (usage - task run -- render -template=simple)
    cmds:
      - go run . {{.CLI_ARGS}}

  render:
    desc: Render a template (usage - task render TEMPLATE=simple)
    vars:
      TEMPLATE: '{{.TEMPLATE | default "simple"}}'
      OUT: '{{.OUT | default ""}}'
    cmds:
      - go run . render -template={{.TEMPLATE}} {{if .OUT}}-out={{.OUT}}{{end}}

  validate:
    desc: Validate HTML file (usage - task validate FILE=email.html)
    vars:
      FILE: '{{.FILE}}'
    cmds:
      - go run . validate -file={{.FILE}}

  send:
    desc: Send test email (usage - task send TO=test@example.com FILE=email.html)
    vars:
      TO: '{{.TO}}'
      FILE: '{{.FILE}}'
    cmds:
      - go run . send -to={{.TO}} -file={{.FILE}}

  list:
    desc: List available templates
    cmds:
      - go run . list -dir=./templates

  # Server
  server:
    desc: Run MCP server
    cmds:
      - go run ./cmd/server

  # Development
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  generate:
    desc: Generate code (templ, goctl)
    cmds:
      - templ generate

  # Data management
  clean:data:
    desc: Clean data cache directory
    cmds:
      - rm -rf {{.DATA_DIR}}

  # Port management
  kill:ports:
    desc: Kill processes on server ports (8080, 8081)
    cmds:
      - lsof -ti:8080 | xargs kill -9 2>/dev/null || true
      - lsof -ti:8081 | xargs kill -9 2>/dev/null || true
      - echo "Ports 8080 and 8081 cleared"
