version: '3'

dotenv:
  - .env

vars:
  DATA_DIR: '{{.ROOT_DIR}}/.data'
  BIN_DIR: '{{.ROOT_DIR}}/.bin'
  API_FILE: api/plat-mjml.api

tasks:
  # --- Development ---
  dev:
    desc: Start server (kills stale ports first)
    deps: [kill:ports]
    cmds:
      - go run ./cmd/server

  run:
    desc: Run CLI (usage — task run -- render -template=simple)
    cmds:
      - go run . {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run go vet
    cmds:
      - go vet ./...

  build:
    desc: Build server and CLI binaries
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/server ./cmd/server
      - go build -o {{.BIN_DIR}}/plat-mjml .
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - '{{.BIN_DIR}}/server'
      - '{{.BIN_DIR}}/plat-mjml'

  check:
    desc: Run lint + test + build
    cmds:
      - task: lint
      - task: test
      - task: build

  # --- Code Generation ---
  gen:
    desc: Regenerate API handlers, types, and swagger from .api file
    cmds:
      - goctl api validate --api {{.API_FILE}}
      - goctl api go --api {{.API_FILE}} --dir . --style gozero
      - rm -f mjml.go && rm -rf etc/
      - goctl api swagger --api {{.API_FILE}} --dir docs --filename swagger
    sources:
      - '{{.API_FILE}}'
    generates:
      - docs/swagger.json
      - internal/types/types.go
      - internal/handler/routes.go

  gen:model:
    desc: Regenerate go-zero models from SQLite DDL schemas
    cmds:
      - goctl model mysql ddl --src schema/templates.sql --dir internal/model --home ./goctl-sqlite --style gozero
      - goctl model mysql ddl --src schema/emails.sql --dir internal/model --home ./goctl-sqlite --style gozero
      - goctl model mysql ddl --src schema/email_events.sql --dir internal/model --home ./goctl-sqlite --style gozero
      - goctl model mysql ddl --src schema/smtp_providers.sql --dir internal/model --home ./goctl-sqlite --style gozero

  gen:all:
    desc: Regenerate everything (API + models + swagger)
    deps: [gen, gen:model]

  gen:template:init:
    desc: Initialize goctl SQLite custom templates
    cmds:
      - goctl template init --home ./goctl-sqlite
    status:
      - test -d ./goctl-sqlite

  # --- Setup ---
  setup:
    desc: Install dependencies and tools
    cmds:
      - go mod download
      - command -v goctl >/dev/null || go install github.com/zeromicro/go-zero/tools/goctl@latest
      - goctl env check --install --verbose

  # --- Cleanup ---
  clean:
    desc: Remove build artifacts and data cache
    cmds:
      - rm -rf {{.BIN_DIR}} {{.DATA_DIR}}

  kill:ports:
    desc: Kill processes on ports 8080/8081/8082
    cmds:
      - lsof -ti:8080,8081,8082 | xargs kill -9 2>/dev/null || true
