version: '3'

dotenv:
  - .env

vars:
  DATA_DIR: '{{.ROOT_DIR}}/.data'
  BIN_DIR: '{{.ROOT_DIR}}/.bin'
  API_FILE: api/plat-mjml.api

tasks:
  # --- Run ---
  server:
    desc: Start MCP server + Web UI + REST API
    deps: [kill-ports]
    cmds:
      - go run ./cmd/server

  run:
    desc: Run CLI (usage - task run -- render -template=simple)
    cmds:
      - go run . {{.CLI_ARGS}}

  # --- Build ---
  build:
    desc: Build all binaries
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/server ./cmd/server
      - go build -o {{.BIN_DIR}}/plat-mjml .
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - '{{.BIN_DIR}}/server'
      - '{{.BIN_DIR}}/plat-mjml'

  # --- Development ---
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  generate:
    desc: Regenerate API code, types, and Swagger docs from .api file
    cmds:
      - goctl api validate --api {{.API_FILE}}
      - goctl api go --api {{.API_FILE}} --dir . --style gozero
      - rm -f mjml.go && rm -rf etc/
      - goctl api swagger --api {{.API_FILE}} --dir docs --filename swagger
    sources:
      - '{{.API_FILE}}'
    generates:
      - docs/swagger.json
      - internal/types/types.go
      - internal/handler/routes.go

  deps:
    desc: Install dependencies and tools
    cmds:
      - go mod download
      - command -v goctl >/dev/null || go install github.com/zeromicro/go-zero/tools/goctl@latest

  # --- Email CLI shortcuts ---
  list:
    desc: List available templates
    cmds:
      - go run . list -dir=./templates

  render:
    desc: Render template (TEMPLATE=simple OUT=file.html)
    vars:
      TEMPLATE: '{{.TEMPLATE | default "simple"}}'
      OUT: '{{.OUT | default ""}}'
    cmds:
      - go run . render -template={{.TEMPLATE}} {{if .OUT}}-out={{.OUT}}{{end}}

  validate:
    desc: Validate HTML (FILE=email.html)
    cmds:
      - go run . validate -file={{.FILE}}

  send:
    desc: Send email (TO=user@example.com FILE=email.html)
    cmds:
      - go run . send -to={{.TO}} -file={{.FILE}}

  # --- Cleanup ---
  clean:
    desc: Remove build artifacts and data cache
    cmds:
      - rm -rf {{.BIN_DIR}} {{.DATA_DIR}}

  kill-ports:
    desc: Kill processes on ports 8080/8081/8082
    cmds:
      - lsof -ti:8080,8081,8082 | xargs kill -9 2>/dev/null || true
