// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	email "github.com/joeblew999/plat-mjml/internal/handler/email"
	stats "github.com/joeblew999/plat-mjml/internal/handler/stats"
	template "github.com/joeblew999/plat-mjml/internal/handler/template"
	"github.com/joeblew999/plat-mjml/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/emails",
				Handler: email.SendEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/emails",
				Handler: email.ListEmailsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/emails/:id",
				Handler: email.GetEmailStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: stats.GetStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/templates",
				Handler: template.ListTemplatesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/templates/:slug",
				Handler: template.GetTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/templates/:slug/render",
				Handler: template.RenderTemplateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
