// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	emailsFieldNames          = builder.RawFieldNames(&Emails{})
	emailsRows                = strings.Join(emailsFieldNames, ",")
	emailsRowsExpectAutoSet   = strings.Join(stringx.Remove(emailsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	emailsRowsWithPlaceHolder = strings.Join(stringx.Remove(emailsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	emailsModel interface {
		Insert(ctx context.Context, data *Emails) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Emails, error)
		Update(ctx context.Context, data *Emails) error
		Delete(ctx context.Context, id string) error
	}

	defaultEmailsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Emails struct {
		Id           string         `db:"id"`
		TemplateSlug string         `db:"template_slug"`
		Recipients   string         `db:"recipients"`
		Subject      string         `db:"subject"`
		Data         sql.NullString `db:"data"`
		Status       string         `db:"status"`
		Priority     int64          `db:"priority"`
		Attempts     int64          `db:"attempts"`
		MaxAttempts  int64          `db:"max_attempts"`
		ScheduledAt  sql.NullTime   `db:"scheduled_at"`
		SentAt       sql.NullTime   `db:"sent_at"`
		MessageId    string         `db:"message_id"`
		Error        sql.NullString `db:"error"`
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newEmailsModel(conn sqlx.SqlConn) *defaultEmailsModel {
	return &defaultEmailsModel{
		conn:  conn,
		table: "`emails`",
	}
}

func (m *defaultEmailsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmailsModel) FindOne(ctx context.Context, id string) (*Emails, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", emailsRows, m.table)
	var resp Emails
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmailsModel) Insert(ctx context.Context, data *Emails) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, emailsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TemplateSlug, data.Recipients, data.Subject, data.Data, data.Status, data.Priority, data.Attempts, data.MaxAttempts, data.ScheduledAt, data.SentAt, data.MessageId, data.Error)
	return ret, err
}

func (m *defaultEmailsModel) Update(ctx context.Context, data *Emails) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, emailsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TemplateSlug, data.Recipients, data.Subject, data.Data, data.Status, data.Priority, data.Attempts, data.MaxAttempts, data.ScheduledAt, data.SentAt, data.MessageId, data.Error, data.Id)
	return err
}

func (m *defaultEmailsModel) tableName() string {
	return m.table
}
