// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	emailEventsFieldNames          = builder.RawFieldNames(&EmailEvents{})
	emailEventsRows                = strings.Join(emailEventsFieldNames, ",")
	emailEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(emailEventsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	emailEventsRowsWithPlaceHolder = strings.Join(stringx.Remove(emailEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	emailEventsModel interface {
		Insert(ctx context.Context, data *EmailEvents) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*EmailEvents, error)
		Update(ctx context.Context, data *EmailEvents) error
		Delete(ctx context.Context, id string) error
	}

	defaultEmailEventsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EmailEvents struct {
		Id        string         `db:"id"`
		EmailId   string         `db:"email_id"`
		EventType string         `db:"event_type"`
		Timestamp time.Time      `db:"timestamp"`
		Details   sql.NullString `db:"details"`
	}
)

func newEmailEventsModel(conn sqlx.SqlConn) *defaultEmailEventsModel {
	return &defaultEmailEventsModel{
		conn:  conn,
		table: "`email_events`",
	}
}

func (m *defaultEmailEventsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmailEventsModel) FindOne(ctx context.Context, id string) (*EmailEvents, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", emailEventsRows, m.table)
	var resp EmailEvents
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmailEventsModel) Insert(ctx context.Context, data *EmailEvents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, emailEventsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.EmailId, data.EventType, data.Timestamp, data.Details)
	return ret, err
}

func (m *defaultEmailEventsModel) Update(ctx context.Context, data *EmailEvents) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, emailEventsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.EmailId, data.EventType, data.Timestamp, data.Details, data.Id)
	return err
}

func (m *defaultEmailEventsModel) tableName() string {
	return m.table
}
