// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	smtpProvidersFieldNames          = builder.RawFieldNames(&SmtpProviders{})
	smtpProvidersRows                = strings.Join(smtpProvidersFieldNames, ",")
	smtpProvidersRowsExpectAutoSet   = strings.Join(stringx.Remove(smtpProvidersFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	smtpProvidersRowsWithPlaceHolder = strings.Join(stringx.Remove(smtpProvidersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	smtpProvidersModel interface {
		Insert(ctx context.Context, data *SmtpProviders) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*SmtpProviders, error)
		FindOneByName(ctx context.Context, name string) (*SmtpProviders, error)
		Update(ctx context.Context, data *SmtpProviders) error
		Delete(ctx context.Context, id string) error
	}

	defaultSmtpProvidersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SmtpProviders struct {
		Id        string        `db:"id"`
		Name      string        `db:"name"`
		Host      string        `db:"host"`
		Port      int64         `db:"port"`
		Username  string        `db:"username"`
		Password  string        `db:"password"`
		FromEmail string        `db:"from_email"`
		FromName  string        `db:"from_name"`
		IsDefault int64         `db:"is_default"`
		RateLimit sql.NullInt64 `db:"rate_limit"`
		CreatedAt time.Time     `db:"created_at"`
	}
)

func newSmtpProvidersModel(conn sqlx.SqlConn) *defaultSmtpProvidersModel {
	return &defaultSmtpProvidersModel{
		conn:  conn,
		table: "`smtp_providers`",
	}
}

func (m *defaultSmtpProvidersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSmtpProvidersModel) FindOne(ctx context.Context, id string) (*SmtpProviders, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", smtpProvidersRows, m.table)
	var resp SmtpProviders
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmtpProvidersModel) FindOneByName(ctx context.Context, name string) (*SmtpProviders, error) {
	var resp SmtpProviders
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", smtpProvidersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmtpProvidersModel) Insert(ctx context.Context, data *SmtpProviders) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, smtpProvidersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Host, data.Port, data.Username, data.Password, data.FromEmail, data.FromName, data.IsDefault, data.RateLimit)
	return ret, err
}

func (m *defaultSmtpProvidersModel) Update(ctx context.Context, newData *SmtpProviders) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, smtpProvidersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Host, newData.Port, newData.Username, newData.Password, newData.FromEmail, newData.FromName, newData.IsDefault, newData.RateLimit, newData.Id)
	return err
}

func (m *defaultSmtpProvidersModel) tableName() string {
	return m.table
}
