// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	templatesFieldNames          = builder.RawFieldNames(&Templates{})
	templatesRows                = strings.Join(templatesFieldNames, ",")
	templatesRowsExpectAutoSet   = strings.Join(stringx.Remove(templatesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	templatesRowsWithPlaceHolder = strings.Join(stringx.Remove(templatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	templatesModel interface {
		Insert(ctx context.Context, data *Templates) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Templates, error)
		FindOneBySlug(ctx context.Context, slug string) (*Templates, error)
		Update(ctx context.Context, data *Templates) error
		Delete(ctx context.Context, id string) error
	}

	defaultTemplatesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Templates struct {
		Id          string         `db:"id"`
		Slug        string         `db:"slug"`
		Name        string         `db:"name"`
		Content     string         `db:"content"`
		Version     int64          `db:"version"`
		Status      string         `db:"status"`
		Category    string         `db:"category"`
		Metadata    sql.NullString `db:"metadata"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
		PublishedAt sql.NullTime   `db:"published_at"`
	}
)

func newTemplatesModel(conn sqlx.SqlConn) *defaultTemplatesModel {
	return &defaultTemplatesModel{
		conn:  conn,
		table: "`templates`",
	}
}

func (m *defaultTemplatesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTemplatesModel) FindOne(ctx context.Context, id string) (*Templates, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", templatesRows, m.table)
	var resp Templates
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTemplatesModel) FindOneBySlug(ctx context.Context, slug string) (*Templates, error) {
	var resp Templates
	query := fmt.Sprintf("select %s from %s where `slug` = ? limit 1", templatesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, slug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTemplatesModel) Insert(ctx context.Context, data *Templates) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, templatesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Slug, data.Name, data.Content, data.Version, data.Status, data.Category, data.Metadata, data.PublishedAt)
	return ret, err
}

func (m *defaultTemplatesModel) Update(ctx context.Context, newData *Templates) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, templatesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Slug, newData.Name, newData.Content, newData.Version, newData.Status, newData.Category, newData.Metadata, newData.PublishedAt, newData.Id)
	return err
}

func (m *defaultTemplatesModel) tableName() string {
	return m.table
}
